export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const ALTERA_PROJETO = 'ALTERA_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

export const NOTIFICAR = 'NOTIFICAR';

export const ADICIONAR_TAREFAS = 'ADICIONAR_TAREFAS';
export const ALTERAR_TAREFA = 'ALTERAR_TAREFA';
export const EXCLUIR_TAREFA = 'EXCLUIR_TAREFA';
export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';